# src/chatbot/templates.py
"""
Templates and synonyms for generating training data.
"""

# Canonical metric names (column names in DB) and their synonyms
METRIC_SYNONYMS = {
    'recovery_score': ['recovery', 'recovery score', 'recovery index', 'recovery level'],
    'movement_score': ['movement', 'movement score', 'movement index', 'activity score'],
    'sleep_score': ['sleep', 'sleep score', 'sleep quality', 'sleep rating'],
    'total_sleep_min': ['total sleep', 'sleep time', 'sleep duration', 'hours slept', 'sleep length'],
    'sleep_efficiency': ['sleep efficiency', 'efficiency', 'sleep quality percentage'],
    'deep_sleep_min': ['deep sleep', 'deep sleep minutes', 'deep sleep duration'],
    'rem_sleep_min': ['rem sleep', 'rem', 'rem duration'],
    'light_sleep_min': ['light sleep', 'light sleep minutes'],
    'avg_temperature': ['temperature', 'skin temperature', 'body temperature', 'avg temp'],
    'total_steps': ['steps', 'step count', 'steps taken'],
    'hrv_avg': ['hrv', 'heart rate variability', 'hrv average'],
    'rhr_avg': ['resting heart rate', 'rhr', 'resting hr', 'night rhr'],
    'active_minutes': ['active minutes', 'activity minutes', 'active time'],
    'vo2_max': ['vo2 max', 'vo2', 'cardio fitness'],
}

# Time expressions for history intent (these will be used as placeholders)
TIME_RANGES = [
    'last 3 days',
    'last 5 days',
    'last week',
    'last 2 weeks',
    'last month',
    'this week',
    'this month',
    'past week',
    'past 10 days',
    'previous 7 days',
    'last 30 days',
    'this year',
    'yesterday',
    'today',
    'the past few days',
    'the last couple of weeks',
    'over the weekend',
]

# Pairs for comparison (time1 vs time2)
COMPARE_PAIRS = [
    ('today', 'yesterday'),
    ('this week', 'last week'),
    ('this month', 'last month'),
    ('Monday', 'Tuesday'),
    ('last 7 days', 'previous 7 days'),
    ('last week', 'the week before'),
    ('this week', 'the previous week'),
]

# Templates for each intent
# The placeholders {metric}, {time_range}, {time1}, {time2} will be filled later.
TEMPLATES = {
    'get_current': [
        "What is my {metric} today?",
        "How is my {metric}?",
        "What is my {metric}?",
        "Show me today's {metric}",
        "Tell me my {metric}",
        "What's my {metric} now?",
        "Current {metric}",
        "What is the value of {metric} today?",
        "Give me my {metric} for today",
        "How did I do on {metric} today?",
        "What's my current {metric}?",
        "Can you tell me my {metric}?",
        "I want to know my {metric}",
        "What is my {metric} right now?",
        "How is my {metric} doing today?",
        "What's today's {metric}?",
        "Do you have my {metric} for today?",
        "Show me my {metric}",
        "Get my {metric}",
        "Tell me the current {metric}",
    ],
    'get_history': [
        "How was my {metric} {time_range}?",
        "What was my {metric} over {time_range}?",
        "Give me my {metric} for {time_range}",
        "Show me {metric} for {time_range}",
        "What is my average {metric} {time_range}?",
        "Tell me the {metric} trend {time_range}",
        "How did my {metric} look {time_range}?",
        "What was my {metric} like {time_range}?",
        "Can I see my {metric} {time_range}?",
        "{time_range} what was my {metric}?",
        "During {time_range}, what was my {metric}?",
        "I'd like to see my {metric} from {time_range}",
        "Show me the history of {metric} for {time_range}",
        "What values did my {metric} have {time_range}?",
        "How did my {metric} change {time_range}?",
        "Tell me about my {metric} over {time_range}",
        "Give me the details of {metric} {time_range}",
        "What was the trend of {metric} {time_range}?",
        "Can you summarize my {metric} for {time_range}?",
    ],
    'compare': [
        "Compare my {metric} {time1} vs {time2}",
        "How does my {metric} compare between {time1} and {time2}?",
        "What's the difference in {metric} between {time1} and {time2}?",
        "Is my {metric} better {time1} or {time2}?",
        "Show me comparison of {metric} for {time1} and {time2}",
        "How did {metric} change from {time2} to {time1}?",
        "Which day had better {metric}, {time1} or {time2}?",
        "Compare {metric} values: {time1} vs {time2}",
        "What is the difference in {metric} between {time1} and {time2}?",
        "How does {time1} {metric} compare to {time2}?",
        "Tell me if my {metric} improved from {time2} to {time1}",
        "Give me a comparison of {metric} between {time1} and {time2}",
    ],
    'advice': [
        # Workout/diet generic
        "What workout should I do?",
        "Give me diet advice",
        "Any workout suggestions?",
        "What should I eat today?",
        "Recovery advice?",
        "Should I work out today?",
        "What's a good workout based on my recovery?",
        "Any diet tips for today?",
        "What activity do you recommend?",
        "What should I eat to optimize recovery?",
        "Any advice for today?",
        "Workout recommendation?",
        "Can you suggest a meal plan?",
        "What kind of exercise is good today?",
        "Do I need rest or training?",
        "What's a good training intensity for today?",
        "Give me some health tips",
        "How should I train today?",
        "What should I focus on today?",
        # Improvement and why questions (will be handled by LLM later)
        "How can I improve my {metric}?",
        "Why is my {metric} low today?",
        "Why has my {metric} gone down recently?",
        "What can I do to increase my {metric}?",
        "Suggestions to improve {metric}",
        "Any tips for better {metric}?",
        "How do I get a higher {metric}?",
        "Why did my {metric} drop?",
        "What caused my {metric} to decrease?",
        "How can I boost my {metric}?",
        "Why is my {metric} not good?",
        "What should I do to raise my {metric}?",
        "Why has my {metric} been low lately?",
        "How to improve my {metric} score?",
        "What affects my {metric} negatively?",
        "How can I make my {metric} better?",
        "Why did my {metric} go down {time_range}?",
        "What made my {metric} decrease over {time_range}?",
        "How can I prevent my {metric} from dropping?",
        "Tips for maintaining good {metric}",
    ]
}
